name: fgpt_ai
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  shared_preferences: ^2.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  injectable: ^1.5.4
  objectbox: ^2.0.0
  objectbox_flutter_libs: ^2.0.0
  objectbox_generator: ^2.0.0
  connectivity_plus: ^3.0.4
  intl: ^0.17.0
  permission_handler: ^10.2.0
  carousel_slider: ^4.2.1
  timeago: ^3.3.0
  dio: ^5.1.1
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2
  flutter_screenutil: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.4
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
